{% set name = "gremlinpython" %}
{% set version = "3.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gremlinpython-{{ version }}.tar.gz
  sha256: 2ebaa1f360ba62c48705b056ba3d4e92e448287431f42a92eef4b2217ae51c5b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - importlib-metadata <3.0.0
    - pip
    - pytest-runner ==5.2
    - python {{ python_min }}
  run:
    - aenum >=1.4.5,<3.0.0
    - aiohttp >=3.8.0,<=3.8.1
    - isodate >=0.6.0,<1.0.0
    - nest-asyncio
    - python >={{ python_min }}
    - six >=1.10.0,<2.0.0

test:
  imports:
    - gremlin_python
    - gremlin_python.driver
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://tinkerpop.apache.org
  summary: Gremlin-Python for Apache TinkerPop
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Luxxii
