{% set name = "gremlinpython" %}
{% set version = "3.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gremlinpython-{{ version }}.tar.gz
  sha256: 348be275821f87213279f25731ab0c6e08f8c971a7cbb44302a165e3f7ad11d8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - importlib-metadata <3.0.0
    - pip
    - pytest-runner ==5.2
    - python >=3.6
  run:
    - aenum >=1.4.5,<3.0.0
    - isodate >=0.6.0,<1.0.0
    - pyparsing >=2.4.7,<3.0.0
    - python >=3.6
    - six >=1.10.0,<2.0.0
    - tornado >=4.4.1,<6.0
    - aiohttp
    - nest-asyncio

test:
  imports:
    - gremlin_python
    - gremlin_python.driver
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://tinkerpop.apache.org
  summary: Gremlin-Python for Apache TinkerPop
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Luxxii
